version: '3'
services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "medscan"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-compose-network

volumes:
  mysql_data:

networks:
  mysql-compose-network:
    driver: bridge
